# POSTGRESQL
- name: Install PostgreSQL
  action: apt name={{ postgresql }}

- name: Install postgres dev
  action: apt name=postgresql-server-dev-all

- name: create db user
  become: true
  become_user: postgres
  postgresql_user: name=vagrant password=vagrant role_attr_flags=SUPERUSER

- name: create dbs
  become: true
  become_user: postgres
  postgresql_db: name=vagrant owner=vagrant
                 encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0'
                 state=present


# SQLITE3
- name: Install Sqlite3
  action: apt name=sqlite3

- name: Install libsqlite3-dev
  action: apt name=libsqlite3-dev

# REDIS
- name: Install REDIS
  action: apt name=redis-server
