# JAVA, SCALA AND CLOJURE
#
- name: Install Java
  action: apt name=default-jdk

- name: Download lein
  command: wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/local/bin/lein

- name: Add permission for lein
  command: chmod a+x /usr/local/bin/lein

- name: Install lein
  command: /usr/local/bin/lein
