# JAVA, SCALA AND CLOJURE
#
- name: Install Java
  action: apt name=default-jdk

- name: Download lein
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /usr/local/bin/lein
    mode: a+x

- name: Install lein
  command: /usr/local/bin/lein
