- name: copy up .bashrc
  become: false
  copy: dest=~/.bashrc src=files/bashrc

- name: Create env directory
  file: path=~/.envs state=directory

- name: Set locale en_US.UTF-8
  command: locale-gen "en_US.UTF-8"

- name: Update locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
