- file:
    path: /home/vagrant/.vim/autoload
    state: directory
    mode: 0777

- name: Download Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/vagrant/.vim/autoload/plug.vim

- name: copy up .vimrc
  copy: dest=/home/vagrant/.vimrc src=files/vimrc
  mode: 0777
